### ISSUE TITLE
Recipes in the examples folder fail to be parsed by pyYAML

### ISSUE THREAD

**Issue by kohaugustine** [techhat/openrecipeformat#5]
Hi,

I just cloned your repository, and tried running the example files through pyYAML. Both of them could not be parsed until I made a simple correction of ensuring that all values of each field key are placed in the same line as the key itself. For example, in lines 90 to 91 of `banana-bread.yaml`, we have:
```
  - step:
    Preheat oven to 350F.
```
but this gives an error:
```
ScannerError: while scanning a simple key
  in "./banana-bread.yaml", line 91, column 5
could not find expected ':'
  in "./banana-bread.yaml", line 92, column 3
```
which goes away only after I convert the data to be:
```
  - step: Preheat oven to 350F.
```
I found a similar problem in other parts of the same file as well as in the `orf-sample-1.yaml`. Is this a bug in the example files that should be corrected? Or were the examples supposed to have worked? Why did pyYAML reject this representation?

Here I've attached the diffs between the original and corrected examples.

[banana-bread.yaml](https://www.diffchecker.com/SLW1hguG)
[orf-sample-1.yaml](https://www.diffchecker.com/nUTsi1Ne)

Thank you.

**Comment by adamvoss** [comment]
I believe you and pyYAML are correct that the example files are not valid YAML.

**Comment by kohaugustine** [comment]
That explains some of the difficulties then. I also wonder if the format as it is currently defined on the [reference documentation](http://open-recipe-format.readthedocs.io/en/latest/topics/reference/orf.html#) can be improved.

For example, when I parse `orf-sample-1.yaml` (after making the syntax correction), I get this python dictionary, a snippet of which I've attached here:
```
In [43]: orf
Out[43]: 
{'author': 'Me',
 'bake_time': 'none',
 'ingredients': [{'amounts': [{'amount': 4, 'unit': 'each'},
    {'amount': 10, 'unit': 'each'}],
   'apple': None,
   'notes': ['Use whole apples',
    'Pears may be substituted, but produce a different flavor and mouthfeel'],
   'processing': ['whole', 'raw'],
   'substitutions': [{'amounts': [{'amount': 4, 'unit': 'each'},
      {'amount': 10, 'unit': 'each'}],
     'pears': None,
     'usda_num': '09252'}],
   'usda_num': '09003'},
  {'amounts': [{'amount': 4, 'unit': 'each'}, {'amount': 10, 'unit': 'each'}],
   'banana': None,
   'usda_num': '09040'}],
.....
```
A humble improvement suggestion. I feel like that the ingredient names should be made easier to access than what the format currently specifies. Right now, in order to build a list of ingredients, one would need to do a double loop such as:
```
In [75]: for i in range(0,len(orf["ingredients"])):
    ...:     for j in orf["ingredients"][i].keys():
    ...:         if orf["ingredients"][i][j] is None:
    ...:             print(j)
    ...:             
apple
banana
```
which doesn't seem at all efficient for something that is such a crucial part of the recipe.

I'm curious to know whether this format is still being actively developed or not. I personally believe it has great potential and that its impetus is really sound. There really needs to be some good data representation format for storing recipe data. Standards are sorely lacking in this area. I would be very keen to work with anyone who wants to take this project further! I am also particularly interested in extending it to modelling other forms of recipe data, such flavor and fragrance compositions, examples of which can be found [here](http://www.thegoodscentscompany.com/demos/df1014611.html). Even in flavor and fragrance compositions, there are sometimes steps that need to be followed (not just a simple mixing of ingredients together) and the ability to record down information of cooking/processing steps is a big plus of the current ORF model in my opinion.

It would be nice if the documentation could also include some explanations on the motivations why the format is defined the way it is, elucidating the thought processes for establishing this format. That would help kick start a discussion on it.

**Comment by techhat** [comment]
@kohaugustine and @adamvoss I am encouraged to see your activity here! As you have noticed, I haven't devoted any time to the ORF in the past couple of years. But I have been spending some time this past month working with the USDA Standard Ref, and doing some recipe scraping and parsing. It's definitely time to get back to work here.

Let me take some time to reacquaint myself with the docs and examples, and I will come back to this discussion as soon as I can.

**Comment by kohaugustine** [comment]
@techhat It is great to know that you are keen to resume development of the ORF, and that you have been working on recipe scraping and parsing projects recently! Similarly, I am currently involved in some analysis projects both for cuisines, that encompass both flavor and nutritional aspects. I look forward to working with you and @adamvoss on the next steps moving forward! @techhat please keep us updated!

**Comment by adamvoss** [comment]
> Right now, in order to build a list of ingredients, one would need to do a double loop such as: [...]

@kohaugustine The examples are also not valid ORF recipes.  Please take a look at [the [at least partially] corrected version in my fork](https://github.com/adamvoss/openrecipeformat/blob/master/examples/orf-sample-1.yaml).  Getting the ingredients would simply be `recipe['ingredients'].keys()`

To me, these issues (#7 and #8) highlight some of the weaknesses of the format, but that will be a writeup for another day.
