### ISSUE TITLE
Develop a JSON Schema

### ISSUE THREAD

**Issue by adamvoss** [techhat/openrecipeformat#9]
I think the most important thing Open Recipe Format could do to encourage adoption would be to have tooling to support its users.

This is somewhat covered by [TODO.rst](https://github.com/techhat/openrecipeformat/blob/master/TODO.rst):

> - Add a syntax checker
> - Add a reference parser

I do not think a syntax checker and custom parser are quite the right approach.  When I was considering using Open Recipe Format, I went looking at how best to validate a file as being compliant and did not find good options.  Long story short, this lead to me building tooling that could be used for this purpose.

If someone wants to apply them to this problem (despite building the tooling as a result of this problem, I do not currently have a need for Open Recipe Format) they would need to write a [JSON Schema](http://json-schema.org/) for the schema of Open Recipe Format.

Then the following would be available:
* Users can use the [YAML extension](https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml) for [Visual Studio Code](https://code.visualstudio.com/) to write their recipes while getting editor help (in the way of feedback if an entry is invalid, completion has not been implemented [but could]) because they specify the Open Recipe Format schema should be used.
  * The extension is [Language Server](http://langserver.org/)-based so someone could port it to other editors if desired.
* Users can validate their recipes via command line using the [Polyglottal JSON Schma Validator (pajv)](https://www.npmjs.com/package/pajv).
* Users looking for tools other than the two just mentioned can check [Schema Validation for YAML at JSON Schema Everywhere](https://json-schema-everywhere.github.io/yaml) to see if anything else has been implemented.
* Users wanting to programatically interact with their recipes using an API other than their YAML parser can look can generate an API from the JSON Schema (ex. [Java](http://www.jsonschema2pojo.org/), [C#](http://json2csharp.rohitl.com/))

**Comment by brmdv** [comment]
Liked this idea, and put something together: [gist](https://gist.github.com/brmdv/24a617176f07e5c57c46c258e7c71f25).
I based it on the official reference, though there where some inconsistencies with the example files. 

To test in VSCode, install the [YAML-extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml), and add this line to your preferences file:
```json
"yaml.schemas": {
        "file://path/to/ORF_schema.json": "*yml"
},
```
